trigger:
- unit-tests

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: Release

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 5.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: DotNetCoreCLI@2  
  displayName: 'dotnet restore'  
  inputs:  
    command: restore  
    projects: '**/*.csproj'  
    includeNuGetOrg: true  
- task: DotNetCoreCLI@2  
  displayName: 'dotnet build'  
  inputs:  
    command: build  
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2  
  displayName: 'dotnet test'  
  inputs:  
    command: test  
    projects: '**/*.Tests.csproj'  
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'  
    testRunTitle: UnitTests

- script: 'dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.8'  
  displayName: 'Install ReportGenerator tool' 

- script: 'reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"'  
  displayName: 'Create reports'

- task: PublishCodeCoverageResults@1  
  displayName: 'Publish code coverage'  
  inputs:  
    codeCoverageTool: Cobertura  
    summaryFileLocation: '$(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml'  